#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_ZTE_SENSORS_ACCEL_LIS3DH)	+= lis3dh_acc.o
obj-$(CONFIG_ZTE_SENSORS_LIGHT_TAOS)	+= taos.o
obj-$(CONFIG_ZTE_SENSORS_ACCEL_MC3XXX)	+= mc3xxx.o
obj-$(CONFIG_ZTE_SENSORS_ACCEL_BMA2XX)	+= bma2xx.o
obj-$(CONFIG_ZTE_SENSORS_COMPASS_AK8963)	+= akm8963.o